# Generated by Django 3.0.4 on 2020-03-08 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covidic', '0002_auto_20200308_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='create_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='covidic.Account'),
        ),
        migrations.AlterField(
            model_name='threaditem',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='references', to='covidic.Archive'),
        ),
    ]
