# Generated by Django 3.0.4 on 2020-03-10 18:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('discord_name', models.CharField(max_length=32)),
                ('discord_id', models.BigIntegerField()),
                ('is_able', models.BooleanField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('token', models.UUIDField(default=uuid.uuid1)),
                ('token_create_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'accounts',
                'unique_together': {('discord_id',)},
            },
        ),
    ]
