# Generated by Django 2.2.11 on 2020-03-07 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('discord_userid', models.BigIntegerField()),
                ('is_able', models.BooleanField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(max_length=36)),
                ('token_create_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='Arhive',
            fields=[
                ('typeof', models.CharField(choices=[('I', 'IMGUR'), ('A', 'ARHIVE')], max_length=1)),
                ('arhive_id', models.AutoField(primary_key=True, serialize=False)),
                ('tags', models.TextField()),
            ],
            options={
                'db_table': 'arhives',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeof', models.CharField(choices=[('A-N', 'Add news'), ('A-T', 'Add timeline'), ('U-T', 'Update timeline'), ('TC-', 'Token Create'), ('A-C', 'Arhive Create'), ('T-C', 'Thread Create'), ('TIC', 'Thread Item Create'), ('ATC', 'Arhive Tag Chanage')], max_length=3)),
                ('desc', models.CharField(max_length=255)),
                ('log_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'logs',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=1024)),
                ('title', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'newses',
            },
        ),
        migrations.CreateModel(
            name='TagOfArhive',
            fields=[
                ('tag_of_arhive_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'tags_of_arhive',
            },
        ),
        migrations.CreateModel(
            name='TimelineAccident',
            fields=[
                ('accident_id', models.AutoField(primary_key=True, serialize=False)),
                ('typeof', models.CharField(choices=[('M', '의료진 감염'), ('N', '국가위생건강위원회 기록'), ('C', '후베이와 우한의 중앙회의'), ('I', '국제 피드백'), ('T', '국면 전환점')], max_length=1)),
                ('title', models.CharField(max_length=128)),
                ('link', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'timeline_accidents',
            },
        ),
        migrations.CreateModel(
            name='TimelineDate',
            fields=[
                ('date_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'timeline_dates',
            },
        ),
        migrations.CreateModel(
            name='ThreadItem',
            fields=[
                ('thread_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account_manager.Arhive')),
            ],
            options={
                'db_table': 'thread_items',
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('thread_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('create_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account_manager.Account')),
            ],
            options={
                'db_table': 'threads',
            },
        ),
    ]
