# Generated by Django 3.0.4 on 2020-03-13 17:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='discord_id',
            field=models.BigIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='discord_name',
            field=models.CharField(editable=False, max_length=32),
        ),
        migrations.AlterField(
            model_name='account',
            name='token',
            field=models.UUIDField(default=uuid.uuid1, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='token_create_time',
            field=models.DateTimeField(null=True),
        ),
    ]
